[project]
name = "bdl-lang"
version = "1.0.0"
description = "Business Data Language (BDL)"
requires-python = ">=3.10"

dependencies = [
  "typer",
  "rich",
  "pandas",
  "lark"
]

[project.scripts]
bdl = "bdl.cli:app"
